### ISSUE TITLE
Font enum for extra fonts doesn't include the extra fonts, but they are used in the initialization.

### ISSUE THREAD

**Issue by tpitman** [ImpulseAdventure/GUIslice-Builder#100]
**Describe the bug**
When I add additional fonts in the GUI and build the source the enum declaration doesn't include the extra fonts, but they are in the initialization code.

**To Reproduce**
1. Add additional dosis font sizes
2. Build project
3. Notice the enum declaration doesn't include extra fonts.

**Expected behavior**
enum to contain all fonts defined.

**Crash log / Project files**
none

**Screenshots**
none

**Version**
- Builder version: 0.15.0
- OS: Mac OS

**Additional context**
Here is the enum that got generated:
`enum {E_TI_DOSIS_BOOK10PT7B,E_TI_DOSIS_BOOK16PT7B,E_TI_DOSIS_BOOK8PT7B
      ,MAX_FONT};`

Here is the init code (notice the 24 point font is there):
`    if (!gslc_FontSet(&m_gui,E_TI_DOSIS_BOOK10PT7B,GSLC_FONTREF_PTR,&dosis_book10pt7b,1)) { return; }
    if (!gslc_FontSet(&m_gui,E_TI_DOSIS_BOOK16PT7B,GSLC_FONTREF_PTR,&dosis_book16pt7b,1)) { return; }
    if (!gslc_FontSet(&m_gui,E_TI_DOSIS_BOOK24PT7B,GSLC_FONTREF_PTR,&dosis_book24pt7b,1)) { return; }
    if (!gslc_FontSet(&m_gui,E_TI_DOSIS_BOOK8PT7B,GSLC_FONTREF_PTR,&dosis_book8pt7b,1)) { return; }

`

**Comment by Pconti31** [comment]
Fixed in release 0.15.b001
