### ISSUE TITLE
Wrong null pointer

### ISSUE THREAD

**Issue by MVogtDD** [ImpulseAdventure/GUIslice-Builder#102]
Hello,

the following code is being generated when using the keypad:

--
  m_pElemKeyPad = gslc_ElemXKeyPadCreate_Num(&m_gui, E_ELEM_KEYPAD, E_POP_KEYPAD,
    &m_sKeyPad, 65, 80, null, &sCfg);
--

However in C. the null pointer is case sensitive, it has to be NULL, not null.

Best regards,
Marcus

**Comment by Pconti31** [comment]
This is a feature to make sure if a font isn't correctly defined you get a compiler error instead of a runtime crash.  The larger question is how did you end up with an undefined font for keypad?
I assume is has more to do with issue 103 so i'm closing this for now.
Paul--
