### ISSUE TITLE
Teensy (ili9341_t3) font issues

### ISSUE THREAD

**Issue by MVogtDD** [ImpulseAdventure/GUIslice-Builder#103]
Hello,

I just had some trouble working around two bugs of the font handling of the current builder (v.0.15.b001):

1. When setting a font under Options->"Keypad" or "Keypadtext", which is not used otherwise (for example for a text label or text button), an invalid font pointer is being used on calling gslc_ElemXKeyPadCreate_Num leading to a runtime crash when the popup is displayed. Workaround: Creating a " " text label with the font being used for Keypad/Keypadtext

2. E_TY_5X8PT7B is being referenced to in the GSLC header file even if the built in font is not being used at all leading to a compiler error. Workaround: Creating a " " text label with the built in font.

I'm using the GUISlice teensy-adagfx-ili9341_t3-xpt2046 config.

Best regards,
Marcus

**Comment by Pconti31** [comment]
Item 1 - Sorry, I don't have a teensy enviroment to test runtime errors so I have contacted calvin to look into this.  The generated code compiles fine and looks the same as arduino which works so we will have to wait on calvin for item 1.

Item2, you need to post a zip file of all of your project files *.prj, *.ino. *_GSLC.h so I can see what is going on.  I have no idea why E_TY_5X8PT7B would be output or where its being referenced without seeing your project.  Also, what font did you set keypad num and text to and is general tab platform set to teensy?

**Comment by Pconti31** [comment]
fixed in hotfix 0.15.b002

**Comment by MVogtDD** [comment]
Thanks a lot, Paul! Your work is very much appreciated.
