### ISSUE TITLE
Request for using keyboard arrow keys to move objects pixel by pixel

### ISSUE THREAD

**Issue by MVogtDD** [ImpulseAdventure/GUIslice-Builder#104]
Hello,

I've got a relatively simple feature request which would by especially great as multiple objects can now be moved:

To move objects pixel by pixel with the keyboard arrow keys.

Thanks for considering the implementation.

Best regards,
Marcus

**Comment by Pconti31** [comment]
I'll look into it.  I assigned it request `#180`

**Comment by Pconti31** [comment]
I did some work on this and I'm sorry to report that while it seems easy java swing makes this hard to do.
The arrow keys are being trapped by the tab panel and I have found no way to grab the arrow keys in my simulation area.  I have tried keymaps, key bindings and key listeners to no avail.  Seems this change is beyond my ability at the moment.

I'll keep this enhancement on my list in case I come up with a solution someday but will  for now close this issue.
Paul--

**Comment by MVogtDD** [comment]
Thanks for your efforts. Why not assign the keys "a s d w" OR adding a modifier to the arrow keys (ctrl, alt, shift or whatever combination) to moving the objects pixelwise, then? I could very well live with a solution like this.

**Comment by Pconti31** [comment]
@MVogtDD I got this working using alt key arrow combinations.  It will be in hotfix 0.15.b003.
Feel free to add a star if you like the new implementation.
Paul--

**Comment by MVogtDD** [comment]
Thank you a LOT! That is really helpful for me. I will do as soon as I have checked it out.
