### ISSUE TITLE
Wrong text colour of text label

### ISSUE THREAD

**Issue by MVogtDD** [ImpulseAdventure/GUIslice-Builder#106]
When the frame is enabled for a Text object, the Frame colour is used as text colour instead of the text colour in the builder. The code however is correctly generated.

Best regards,
Marcus

**Comment by Pconti31** [comment]
This is actually an issue for GUIslice API not the Builder.  (I don't have write access to API source code or
the repository).
You might want to close it here and open a new one inside GUIslice repository so it doesn't get lost.
Paul--

**Comment by ImpulseAdventure** [comment]
No need to close the issue as I can transfer it.

Could you try the following so I can take a look:
- modify your Builder project’s text element to set the frame color to red, text color to blue and frame enabled
- generate the sketch. From what you described, this may result in red text
- attach a zip file of the Builder project & generated sketch

Thx

**Comment by MVogtDD** [comment]
Sorry I think you misunderstood me. It **is** a builder issue, not a GUISLICE issue.

Please do the following to reproduce the error:
1. Place a text element
2. Enable "frame" ==> The text colour preview changes from yellow to grey (it should stay yellow).

**Comment by Pconti31** [comment]
@MVogtDD I reproduced the problem and assigned bug `#183`.
The fix will be in hotfix 015.b004
Paul--
