### ISSUE TITLE
App window not controllable with some themes

### ISSUE THREAD

**Issue by DonpK** [ImpulseAdventure/GUIslice-Builder#112]
Problem with Ver.  builder-win-0.15.b004 is similar to Issue #59. With some themes including Windows, Windows Classic and Nimbus, the Title Bar is missing and the app window can't be sized or moved.  Most of the other themes appear to work fine.

Problem did not happen with previously installed Ver. Builder 0.14.b004.

OS: Windows 10

**Comment by Pconti31** [comment]
@DonpK  Yes, the old java built in themes do not support the new windows 10 Look and Feel where the menu bar is now moved up into the title line. 
You will have to use the new modern FlatLaf or Intellij themes until the next release 0.15.b006
The next release will detect using the OLD themes and avoid the new look just for them.  
Paul--

**Comment by DonpK** [comment]
Thanks for the feedback. Not a problem; as I said most of the themes work fine and there are plenty to choose from.

Thanks, also, for all your work. I look forward to checking out the new features. Right off the bat, I'm pleased to see the Alt+arrow keys capability to fine-tweak element positioning.
Don
