### ISSUE TITLE
Builder: Value modification: unreadable (on Linux)

### ISSUE THREAD

**Issue by pierbout** [ImpulseAdventure/GUIslice-Builder#113]
### Describe the bug
When I double-clic on a field of the builder to modify the value, this value is unreadable (top and bottom of the field are not visible (at least under Linux Mint 19). When I press enter, the value is visible again

### Device hardware
-Linux Mint 19
- openjdk 11.0.7 2020-04-14
      OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
      OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
-  *MCU*:  ATmega 328P
- *Display with link*:  Adafruit ILI9225
- *GUIslice config selected*:  `ard-adagfx-ili9225` or `ard-adagfx-ili9225-due`

### Checklist to try first
*Most display/touch issues can be identified by working through the steps in the [Configuring GUIslice](https://github.com/ImpulseAdventure/GUIslice/wiki/Configuring-GUIslice) guide.*

*Please confirm whether:*
- *Display works correctly with standalone display driver library examples (eg. TFT_eSPI graphicstest, Adafruit graphicstest, etc.) without GUIslice:* yes
- *Touch works correctly with standalone touch library examples without GUIslice:* ???

### Expected behavior
When I double-clic on a field of the builder to modify the value, I vould expect the cursor to appear, the color of the field to change (or not), but the value to remain parfaitly readable

### Initialization messages
*Please copy any startup messages / errors reported to the serial monitor window here. You can enable all error messages by setting `DEBUG_ERR 2` in the GUIslice config file.*

### Additional info
I think the problem is linked to the GUIslice builder, not the GUIslice library. I think its a matter of field height, as the top and bottom of the field are suddenly missing.After pressing enter, the field height is normal again (and the value readable)

**Comment by pierbout** [comment]
Hello Paul.

Thank you for your quick answer.

I love your builder, and you made an amazing job. I perfectly understand that you do your best and that it's hard to manage any Os in the world. Sorry if I hurtted you, it was really not the goal: I opened this case in order to help you make the builder be even better, not to criticize the amazing job that you did.

I tested with a songle click, and the behaviour is almost the same:
-When I single click, the area is selected (it is almost unnoticeable) and the value remains visible
-but as soon as I start to type a new value, the area becomes grey and the value unreadable
-when I select enter to confirm the new value, the new value is visible (and readable).

**Comment by Pconti31** [comment]
Hmm, I wonder if single click could be java theme related?  What theme are you using?
The Default Flat Light theme? or some other?   If so, try one of the Java built in themes.
Like Metal, or Nimbus.  I am about to update to FlatLaf 0.41 from your installed FlatLaf 0.38 so
if the java themes work we can try an updated FlatLaf version.
Otherwise, I'll have to install mint 20.04 and see if I can determine what is going on.  Although, that could be weeks away given my current load...
Paul--

**Comment by pierbout** [comment]
Hello Paul.

Changing the theme (GTK+) did not solve.

But reinstalling GUIslice-builder with java "~/arduino-1.8.7/java", as you suggested in another post, solved the problem. Thank you for your help!

Issue solved.
