### ISSUE TITLE
Add shortcut [ctrl] + [z] 

### ISSUE THREAD

**Issue by kinafu** [ImpulseAdventure/GUIslice-Builder#115]
**Describe the solution you'd like**
Having the keyboard shortcut `ctrl + z` would be nice to undo actions.
(And `ctrl + y` to re-apply changes after undo)

The undo / redo functionality is already implemented (see buttons in the top bar).

**Comment by Pconti31** [comment]
@kinafu Thanks you for your input.  I will investigate this for release 0.15.b006
or if it turns out to be too complicated a release further out. 
Paul--

**Comment by Pconti31** [comment]
Turns out the next release will be 0.16.0 tied to GUIslice API 0.16.0 due to some changes in the new API.

**Comment by Pconti31** [comment]
Fixed in Release 0.16.0
