### ISSUE TITLE
Selecting Items on Other Pages Doesn't Show All Properties

### ISSUE THREAD

**Issue by tpitman** [ImpulseAdventure/GUIslice-Builder#118]
**Describe the bug**
When I click on an element in the tree view that is on a different page than the current page, the only properties that show in the property window are the ID and ENUM.

**To Reproduce**
1. Have a project with multiple pages open
2. Select and element in a page other than the current page
3. Notice the properties window only populates the ID and ENUM properties
4. Click on either the page or another element in the same page
5. Notice now the properties all populate

**Expected behavior**
All properties should show up any time you click on an element no matter what page it is on.

**Screen Recording**
[https://drive.google.com/file/d/135soHpUNtPRWDtzKcoW0LjS9URZma-LZ/view?usp=sharing](https://drive.google.com/file/d/135soHpUNtPRWDtzKcoW0LjS9URZma-LZ/view?usp=sharing)

**Version**
- Builder version: 0.15.0.b005
- OS: Mac OS

**Comment by Pconti31** [comment]
@tpitman I found the problem and it will be fixed in the next release 0.16.0
Paul--

**Comment by tpitman** [comment]
That is great news. Thanks

**Comment by Pconti31** [comment]
Fixed in Release 0.16.0
