### ISSUE TITLE
gslc_GetImageFromRAM creates const pointer

### ISSUE THREAD

**Issue by farfarfromhome** [ImpulseAdventure/GUIslice-Builder#126]
**Describe the bug**
Adding Image Element and selecting gslc_GetImageFromRAM creates const unsigned character* pointer whereas GUIslice expects unsigned character* pointer for RAM.

**To Reproduce**
1. Add image button or image element to page.
2. Select gslc_GetImageFromRAM for Image Memory value.
3. Generate Code and check that xx_GSLC.h indeed creates const pointer which subsequently causes compile error.   

**Version**
- Builder version: 0.15.b005
- OS: Windows
- Platform: tft_espi

**Comment by Pconti31** [comment]
@farfarfromhome I have assigned this bug #194 and will fix for release 0.16.0 which I hope will be soon.
Paul--

**Comment by Pconti31** [comment]
Fixed in Release 0.16.0
