### ISSUE TITLE
GUISlice crashing after clikcing generate code

### ISSUE THREAD

**Issue by rvxfahim** [ImpulseAdventure/GUIslice-Builder#134]
GUISlice crashing after clikcing generate code

[20201128_194908.txt](https://github.com/ImpulseAdventure/GUIslice/files/5610685/20201128_194908.txt)
[builder.log](https://github.com/ImpulseAdventure/GUIslice/files/5610686/builder.log)

[project file.zip](https://github.com/ImpulseAdventure/GUIslice/files/5610688/project.file.zip)

**Comment by Pconti31** [comment]
@rvxfahim The Builder had a couple of problems with your case statements.  One was the lines with all spaces and the other was the:
```
          if (y==18)
          {break;}
```
which when detected caused the builder to think the case statement was ended.
All of which is is fixed in HotFix 0.16.b002
Paul--
