### ISSUE TITLE
Question about gui builder

### ISSUE THREAD

**Issue by ldijkman** [ImpulseAdventure/GUIslice-Builder#138]
Hello

i am lost
would like to try the gui designer
but i do not know if it will run on raspberry pi400
i use arduino so i have java
if possible, please tell me what to download and howto install
greet luberth
https://oshwlab.com/l.dijkman/esp32-dev-kit-38-pin-to-spi-touch-tft

**Comment by Pconti31** [comment]
@ldijkman Sorry, I don't own a raspberry pi so I have no idea if the builder will work or not.  Or how well if it does run.  

However, if you have Arduino IDE up and running then I say its worth a try.  Follow the instructions for Linux Option A in the wiki.
[Builder Install on Linux](https://github.com/ImpulseAdventure/GUIslice/wiki/Builder-_-Installation-_-LINUX)

Use the latest version builder-linux-0.16.b003.tar.gz

If you try it; Let us know if it works.

Paul--

**Comment by ldijkman** [comment]
thank you 
this is a much better install instruction then the one i have read 
i will try again
https://www.youtube.com/watch?v=qNYT64CaLEI

**Comment by ldijkman** [comment]
downloaded the linux version
 https://github.com/ImpulseAdventure/GUIslice-Builder/releases/download/v0.16.b003/builder-linux-0.16.b003.tar.gz
unpacked it
i see no install.sh in the guibuilder directory?


Enter the new GUIsliceBuilder folder
cd GUIsliceBuilder
Run the installer and indicate where the Java 8 files are located.
./install.sh

**Comment by ldijkman** [comment]
in the sripts directory there is a ./install.sh 
but
pi@raspberrypi:~/gui_slice/GUIslice-Builder-master/builder/scripts $ ./install.sh
bash: ./install.sh: Permission denied

pi@raspberrypi:~/gui_slice/GUIslice-Builder-master/builder/scripts $ sudo ./install.sh
sudo: ./install.sh: command not found

**Comment by ldijkman** [comment]
ok i did now unpacked like you said
Download and untar builder-linux-X.Y.Z.tar.gz
then i have a install.sh  direct in the guibuilder directory 

will try again

**Comment by ldijkman** [comment]
thank you

i now have an icon on the desktop
and it launches the editor
perfect

**Comment by ldijkman** [comment]
did a quick test of the screen editor
think this program can be handy for screen layout
i saw some data  in the generated project code that can be useful
thank you

**Comment by Pconti31** [comment]
@ldijkman Thank you for the information and sorry it was so hard.  If you have any suggestions on how to make the wiki install instructions easier to follow let me know and I'll pass it along to Calvin.
Paul--

**Comment by ldijkman** [comment]
i used the unzip from filemanager that did not  unzip it correct

next is the install text i have seen 
verry confussing to me
download win..................
and then your talking about untar a linux...........................l

Download and untar builder-win64-1.0.tar.gz into your home directory.
Open a terminal
cd $HOME
tar xvzf builder-linux64-1.0.tar.gz

better make a video on youtube howto install on linux and or raspberry linux
i think a lot of people will like your program
maybe im talking nonses but i whas looking for some scalable code generation
generate a square based on window width height
but i can also make 3 different codes for 3 sizes screens
*****************
 

If you are using Arduino IDE's skip to LINUX GUIsliceBuilder SETUP.

LINUX GUIsliceBuilder SETUP
===========================

Download and untar builder-win64-1.0.tar.gz into your home directory.
Open a terminal
cd $HOME
tar xvzf builder-linux64-1.0.tar.gz

Then enter the new GUIsliceBuilder folder
cd GUIsliceBuilder

Then run the installer and answer where to find your Java 8 files.

./install.sh

Your GUIsliceBuilder should now be on your Desktop.

LINUX run the Builder
=====================
Clicking on the GUIslice Icon on your Desktop will open the builder.
You can also run the builder by: 
./GUIslice.sh

**Comment by Pconti31** [comment]
Thanks for the feedback.
