### ISSUE TITLE
Text button frame cannot be disabled

### ISSUE THREAD

**Issue by TobiasPatzel** [ImpulseAdventure/GUIslice-Builder#139]
Hi,

I want to create a text button without a frame. The problem is, when I create a new text button and select in properties "Frame Enabled": "False", the frame is still displayed on the display.

When I select "True" in .ino-file a line is created with the following content: `gslc_ElemSetFrameEn(&m_gui,pElemRef, true);` and a frame is drawn.
When I select "False" no line is created and the library still draws a frame.

In my opinion a line should be created with following content: `gslc_ElemSetFrameEn(&m_gui,pElemRef, false);`.

**Version**
- Builder version: 0.16.b003
- OS: Windows

Thanks, Tobias.

**Comment by Pconti31** [comment]
@TobiasPatzel Agreed.  The code generation is incorrectly testing for frame enabled.
I'll make a HotFix 0.16.b004 soon.
Paul--

**Comment by Pconti31** [comment]
Fixed with Release 0.16.b004
