### ISSUE TITLE
font issue in 0.16b4

### ISSUE THREAD

**Issue by nawazawanswl** [ImpulseAdventure/GUIslice-Builder#143]
fatal error occurs while selecting NotoLatin1
when size of font is > 28

os = win 7 64 bit
[builder-12-30-2020-1.log.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/5757384/builder-12-30-2020-1.log.zip)
[20201231_184555.txt](https://github.com/ImpulseAdventure/GUIslice-Builder/files/5757386/20201231_184555.txt)

**Comment by Pconti31** [comment]
@nawazawanswl Oops! Used short where I should have used an int.
Fixed in next hotfix 0.16.b5
Paul--

**Comment by Pconti31** [comment]
Fixed in 16.b005

**Comment by nawazawanswl** [comment]
thanks...............that was quick
