### ISSUE TITLE
touch events

### ISSUE THREAD

**Issue by nawazawanswl** [ImpulseAdventure/GUIslice-Builder#149]
hi,
i am facing an issue while pressing touch button.
all the 3 event 
move_in
up_in
down_in

how can i fix that, 
i want to use them as we use click event under windows.

**Comment by Pconti31** [comment]
@nawazawanswl Sorry, I'm sure we are facing a language problem here.
I really have no idea what your real question happens to be.   Not sure if you are requesting
enhancements to the Builder or how to use the GUIslice API.

If you are posting a question about using GUIslice API you need to post the question to
[GUIslice API issues](https://github.com/ImpulseAdventure/GUIslice/issues)

I don't have anything to do with the API.  I'm just a member of the user community  like you that simply wrote the Builder and donated it to @ImpulseAdventure .

Now if you post your question to GUIslice API I suggest you try to tell what it is you are trying to accomplish.   Or post a small sample app that shows your problem.  Calvin @ImpulseAdventure or another user in the community will answer you.

Paul--

**Comment by nawazawanswl** [comment]
thanks,
i will post in API section
