### ISSUE TITLE
Doesn't clean code on GuiSlice Builder if you add and remove some controls

### ISSUE THREAD

**Issue by lbarcella** [ImpulseAdventure/GUIslice-Builder#152]
Hi,
  try this...

Put on your screen a text input control or number input control and generate code.
Next remove it and generate one more time

In you code generate remain previous instruction and build on CPU fail

**Check this function, because remain dirty.**

bool CbKeypad(void* pvGui, void *pvElemRef, int16_t nState, void* pvData)
{
  gslc_tsGui*     pGui     = (gslc_tsGui*)pvGui;
  gslc_tsElemRef* pElemRef = (gslc_tsElemRef*)(pvElemRef);
  gslc_tsElem*    pElem    = gslc_GetElemFromRef(pGui,pElemRef);

  // From the pvData we can get the ID element that is ready.
  int16_t nTargetElemId = gslc_ElemXKeyPadDataTargetIdGet(pGui, pvData);
  if (nState == XKEYPAD_CB_STATE_DONE) {
    // User clicked on Enter to leave popup
    // - If we have a popup active, pass the return value directly to
    //   the corresponding value field
    switch (nTargetElemId) {
//<Keypad Enums !Start!>
//<Keypad Enums !End!>
      case E_ELEM_TEXTINPUT4:
        gslc_ElemXKeyPadInputGet(pGui, m_pElemInTxt4, pvData);
	    gslc_PopupHide(&m_gui);
        break;
      case E_ELEM_TEXTINPUT5:
        gslc_ElemXKeyPadInputGet(pGui, m_pElemInTxt5, pvData);
	    gslc_PopupHide(&m_gui);
        break;
      case E_ELEM_TEXTINPUT6:
        gslc_ElemXKeyPadInputGet(pGui, m_pElemInTxt6, pvData);
	    gslc_PopupHide(&m_gui);
        break;
//<Keypad Enums !End!>

Thank you all !

**Comment by lbarcella** [comment]
Thank you Paolo for your answer. I'm happy to use your library... very good job.

**Comment by Pconti31** [comment]
This is working in Release 0.16.b010
