### ISSUE TITLE
DEL button on keyboard causes crash

### ISSUE THREAD

**Issue by MickTheMechanic** [ImpulseAdventure/GUIslice-Builder#154]
**Describe the bug**
Using the DEL button the the keyboard to delete an element causes the program to crash

**To Reproduce**
1. Create a new project
2. Add an element
3. Use the DEL button to delete the element

**Crash log / Project files**
[20210206_233713.txt](https://github.com/ImpulseAdventure/GUIslice-Builder/files/5937802/20210206_233713.txt)

**Version**
- Builder version: b007
- OS: Windows

**Comment by Pconti31** [comment]
Fixed with HotFix 0.16.b008
Paul--
