### ISSUE TITLE
Copy paste causes crash

### ISSUE THREAD

**Issue by MickTheMechanic** [ImpulseAdventure/GUIslice-Builder#155]
**Describe the bug**
If an imagbutton is copied and then pasted twice the system crashes

**To Reproduce**
1. Create a new project
2. Add an image button
3. Copy the element then paste two copies

**Expected behavior**
Multiple copies should be able to be pasted

**Crash log / Project files**
[20210206_234152.txt](https://github.com/ImpulseAdventure/GUIslice-Builder/files/5937808/20210206_234152.txt)

b007
Windows

**Comment by Pconti31** [comment]
Fixed with Release 0.16.b008
Paul--
