### ISSUE TITLE
Code Generation Failed

### ISSUE THREAD

**Issue by fpan-UST** [ImpulseAdventure/GUIslice-Builder#157]
The issue: After adding widgets like sliders, toggles or listboxes, the builder will fail to generate C code. 
Error message: "Code Generation Failed: builder.codegen.CodeGenException: Missing template: <SEEKBAR_CB_CASE>"
Platform: Windows 10
Target platform: Raspberry Pi
Builder version: 0.16.b005
JDK version: 15

**Comment by fpan-UST** [comment]
Actually I figured it out myself. The <SEEKBAR_CB_CASE> segment for code generation was missing in the templates/linux.t file. Just put the following:
`<SEEKBAR_CB_CASE>
    case $<COM-002>:
      // Fetch the slider position
      nVal = gslc_ElemXSeekbarGetPos(pGui,$<COM-019>);
      break;
<STOP>`

into linux.t and the builder will generate the C code with no further issue. I'm closing this issue now.

**Comment by Pconti31** [comment]
fixed in release 0.16.b010
