### ISSUE TITLE
qrcode control Feature request

### ISSUE THREAD

**Issue by todosrc** [ImpulseAdventure/GUIslice-Builder#159]
How to implement QRCode?
https://github.com/yoprogramo/ESP_QRcode

**Comment by Pconti31** [comment]
@todosrc First no additional support is required by GUIslice to output QR Codes.  You simply need to choose a library that supports many different displays.   The  [Arduino QRCODE library](https://github.com/ricmoo/QRCode) works well. To use this library you just need to create a UI element Box the size of your QR Code output + 1 extra pixel for the frame, then in the Property View for this box set "Draw Function=true".   After you do a code generation edit the CbDrawScanner() function to draw your QR Code.  You also need to encode your text string inside the setup() function.

I put together a demo using this library with an ESP32, a 320x240 TFT screen using TFT_eSPI display library. It simply outputs the QR Code for "Hello World".   Hopefully, it has enough detail to explain how you can do the same.
[test_qrcode.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/6710072/test_qrcode.zip)

Paul--
