### ISSUE TITLE
#error No config selected in GUIslice_config.h. Please uncomment/select a config.

### ISSUE THREAD

**Issue by SuperPauly** [ImpulseAdventure/GUIslice-Builder#160]
Why am I getting this error when I have uncomented the driver I need?
![image](https://user-images.githubusercontent.com/5921578/110969809-04bcbe00-8351-11eb-9c20-e458e9acf333.png)
Its the only config I have uncomented and I don't understand why it not compiling.

I have put a config folder in my project and inside that the "ard-adagfx-st7735-notouch.h" driver.
Where am I going wrong?

Thanks.

**Comment by Pconti31** [comment]
@SuperPauly Remove config folder from your project folder.  It must be in libraries/GUIslice/config
Due to an unfortunate medical issue I won't have time for Builder support for the next few months.
If you need more support post to GUIslice issues and Calvin @ImpulseAdventure will help you out.
Paul--

**Comment by Pconti31** [comment]
@SuperPauly One more point GUIslice_config.h must be in libraries/GUIslice/src
Paul--

**Comment by SuperPauly** [comment]
> 
> 
> @SuperPauly Remove config folder from your project folder. It must be in libraries/GUIslice/config
> Due to an unfortunate medical issue I won't have time for Builder support for the next few months.
> If you need more support post to GUIslice issues and Calvin @ImpulseAdventure will help you out.
> Paul--

Thank you for your help, I hope you get and feel better soon. All the best.

**Comment by SuperPauly** [comment]
![image](https://user-images.githubusercontent.com/5921578/110980305-9df1d180-835d-11eb-97f4-83afea341ada.png)
I think it might be a path problem. This is my tree. 

I feel that I got a bit confused with the instructions and have put things in the wrong place. Are the paths now correct?
I also have downloaded the folder with the config files in.

**Comment by Pconti31** [comment]
@SuperPauly To verify, Open Arduino IDE and select File->preferences under Sketchbook location you should see something like: C:\Users\pauls\Documents\Arduino this is where your libraries folder should be along with C:\Users\pauls\Documents\Arduino\libraries\GUIslice, C:\Users\pauls\Documents\Arduino\libraries\Adafruit_GFX and all other arduino libraries.
Edit or replace C:\Users\pauls\Documents\Arduino\libraries\GUIslice\src\GUIslice_config.h here. Same with 
C:\Users\pauls\Documents\Arduino\libraries\GUIslice\config\ard-adagfx-st7735-notouch.h
Again repost in [GUIslice issues](https://github.com/ImpulseAdventure/GUIslice/issues) for more help.

**Comment by Pconti31** [comment]
@SuperPauly Since I haven't heard anything back I'll assume this is fixed. If not add more detail and I'll reopen.
Paul--
