### ISSUE TITLE
Program freezes computer when launching it.

### ISSUE THREAD

**Issue by ariknel** [ImpulseAdventure/GUIslice-Builder#161]
When starting the program, it freezes my computer. 
I am using builder-0.16.b008

EDIT: So when turning off instant replay (Nvidia shadowplay), the program launches properly.

Still annoying tho :)

**Comment by Pconti31** [comment]
@ariknel This appears to be a known issue with Nvidia shadowplay and various Java games and programs.  I'm not aware of anything I can do to fix this.  You should have Nvidia address this issue.
Paul--
