### ISSUE TITLE
Display only text

### ISSUE THREAD

**Issue by nawazawanswl** [ImpulseAdventure/GUIslice-Builder#163]
how can i change " display only text " in runtime ?

**Comment by nawazawanswl** [comment]
i implemented the following code
is the following way correct ?

                                          m_RateLBL->pElem->pStrBuf = "123";
					  gslc_ElemSetRedraw(&m_gui, m_RateLBL,gslc_teRedrawType(1));

**Comment by Pconti31** [comment]
@nawazawanswl I would suggest reading the faq. In particular, "Can you change a Text String at runtime?"
[FAQ](https://github.com/ImpulseAdventure/GUIslice-Builder/releases/download/v0.16.b008/FAQ.pdf)

I'm sorry, but I'm unable to provide much more support at the moment.

Paul--

**Comment by Pconti31** [comment]
Answered in GUIslice API issue `#362`
