### ISSUE TITLE
Fill enable , Disable not working with text input

### ISSUE THREAD

**Issue by nawazawanswl** [ImpulseAdventure/GUIslice-Builder#167]
hi,
program does not show change in gui designer when fill enable disable is selected.
plz correct,
![Fill Error](https://user-images.githubusercontent.com/76815720/112201898-91f5f180-8c32-11eb-8ff8-20fe482ff509.png)

**Comment by Pconti31** [comment]
@nawazawanswl Sorry, I'm wrong this is still broken in latest release.  I tested Text not TextInput.
Due to personal issues it will be a month or two before I can get around to fixing this.
Paul--

**Comment by Pconti31** [comment]
Fixed in Release 0.16.b010
