### ISSUE TITLE
Textbox double quotes are not escaped in generated code

### ISSUE THREAD

**Issue by LowPowerLab** [ImpulseAdventure/GUIslice-Builder#169]
For instance if you type **word "quote" word** in the Text attribute of a textbox, it will be generated as:

`(char*)"word "quote" word",0,E_FREESANS9);`

instead of:

`(char*)"word \"quote\" word",0,E_FREESANS9);`

And this will generate a compile error. This may be true of other generated Text attributes.

**Comment by Pconti31** [comment]
Fixed in 0.16.b011
