### ISSUE TITLE
Need documentation on merging tags with GUISlice Arduino Configuration

### ISSUE THREAD

**Issue by marcwolf1960** [ImpulseAdventure/GUIslice-Builder#170]
Hi.
I was working on a Arduino project using a template generated by GUISlice builder, and I needed to modify the screen layout. 
Unfortunately during the resultant merge of the new code my existing code was damaged.

Can we get some guidelines on what the GUISlice Builder will modify, and what it will not. Especially  the !Start and !End tagging
Many thanks
Dave

**Comment by Pconti31** [comment]
@marcwolf1960 First you shouldn't have lost any code unless you delete it.  The Builder never overwrites your code it just renames it.  The latest version of your code will be called *.bak while inside the folder gui_backup will be all other versions, each named *.ino.##n where n varies from 1 to largest number required.  Just check the dates to find you best option.

If you read the user guide you will notice in the intro this statement:
An important design goal was to allow for incremental (round-trip) revisions between user code updates and Builder visual element adjustments.

You will notice in the generated C code various tags inserted by the builder such as:

```
//<Save_References !Start!>
//<Save_References !End!>
```

As long as you refrain from adding or modifying code between these auto-generated tags you can continue to add additional elements to your project and not lose any other edits you make.   

The only exception is the button callbacks:
```
//<Button Enums !Start!>
//<Button Enums !End!> 
```
Here the user guide documents in ***Appendix E - Case Statement Generation*** the Builder logic in doing edits.
Paul--
