### ISSUE TITLE
Add and use Russian font

### ISSUE THREAD

**Issue by stavtexno** [ImpulseAdventure/GUIslice-Builder#178]
Hello Calvin!!! Thank you for this project! Answer please, how i can use Russian font?

**Comment by stavtexno** [comment]
I use ESP -32 and TFT-eSPI

**Comment by Pconti31** [comment]
@stavtexno In that case read the UserGuide 5.7 Adding Fonts looking at how I added a Chinese VLW font  for ESP32 and TFT_eSPI driver then look closely at Appendix G - Creating VLW Fonts.   If you run into any problem just ask.
Paul--
