### ISSUE TITLE
Possible errors in generated code output

### ISSUE THREAD

**Issue by asgvirtua** [ImpulseAdventure/GUIslice-Builder#182]
Hi Chaps,

Thank you so much, amazing work you're doing here!

With the huge caviat that I'm new to Arduino and C/C++, I'm experiencing compile errors with the header code generated from Builder. Specifically with `gslc_tsRect` and `gslc_tsColor` 

For example, generated code such as `(gslc_tsRect){110,181,200,50}` or `(gslc_tsColor){GSLC_COL_GRAY}` produce expected expression errors.

However if I alter the code to `(gslc_tsRect{110,181,200,50}))` or `(gslc_tsColor{GSLC_COL_GRAY})` the file compiles and works fine (on Arduino Mega)

I've spent a while doing the Google thing and haven't come up with any hits, so I suspect that it's something I've missed :)

Cheers
Si

**Comment by Pconti31** [comment]
What version number of Arduino ide you are using?
Can you create a zip file of the failing project?
Can you or have you tried compiling any of the samples inside GUIslice\Examples\builder?
Paul--

**Comment by asgvirtua** [comment]
Hi Paul, many thanks for the reply, and apologies for wasting your time.

I was using Visual Studio 2022 Community with  vMicro, the Arduino IDE for VS. I've now opened the files in both the official Arduino IDEs, 1.8.15 and 2.0.0 rc3, and it compiled and uploaded no problem. 

Thanks again :)
