### ISSUE TITLE
Ramp Gauge not inspecified position on screen

### ISSUE THREAD

**Issue by u1550l** [ImpulseAdventure/GUIslice-Builder#186]
**Describe the bug**
The Ramp Gauge is displayed in a wrong region on the screen

**To Reproduce**
1. place a ramp gauge on the page
2. resize ramp gauge
3. generate 
4. generated gslc_ElemXRampCreate() call seems correct,
5. when running on arduino target the gauge is not in the correct position

**Expected behavior**
gauge should be drawn at specified position

**Crash log / Project files**
[123bms-V2b.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/8005624/123bms-V2b.zip)

**Screenshots**
![_20220204_193930](https://user-images.githubusercontent.com/31414083/152590161-fd29d4b8-16dc-4721-ab19-0e1f3fcb5603.JPG)
Note: 
I put a black box behind the expected region on the screen.
the gauge region is partially outside the screen (320x240pix)

**Version**
- Builder version: 0.17.b04
- OS: Windows 10

Maybe it is a GUIslice library issue, rather than a Builder issue?

**Comment by Pconti31** [comment]
@u1550l Yes, this appears to me either an API or APP issue.   I don't support the API so you will need to repost to GUIslice issues. However, first create a small test project using just the ramp gauge and hard coded sample data. 

I notice you have a serial print before the ramp update so just copy that data into an array and feed it to your test ramp project, if necessary, to reproduce. 

Zip test with the containing project folder.

Paul--
