### ISSUE TITLE
Serialize zoom factor on save

### ISSUE THREAD

**Issue by dirkx** [ImpulseAdventure/GUIslice-Builder#188]
**Describe the solution you'd like**

When working with small screens (e.g. 320x240) one always has to zoom quite a bit. Would be nice if the (last used) zoom setting would also be serialised in the *.proj file.

**Additional context**

Just a nice to have. Totally not essential.

**Comment by Pconti31** [comment]
@dirkx Yes, I think that's a good idea.  I'll look into it.

Paul--

**Comment by Pconti31** [comment]
@dirkx Now supported in Release 0.17.b05

Paul--

**Comment by dirkx** [comment]
lovely!
