### ISSUE TITLE
Builder some Elements Height/width reset to default when moved

### ISSUE THREAD

**Issue by nadjet09** [ImpulseAdventure/GUIslice-Builder#190]
**Describe the bug**
If Textinput, NumberInput, or just text box placed in the project with specific font size, their own Height/Width will be generated automatically. even though the height and width is possible to modify it will change back to default height and width if developer decided to move the element. It may not be a big of a trouble if it's a single or few elements, but it happens that the elements are a lot. and during the project development ideas changes, and all element needed to move up/down or left/right. this will bring all elements to default height/width, and it's time consuming to keep entering the height/width individually multiple times  .
this could be one time change and doesn't matter if element is moved it should keep the new dimensions.

**To Reproduce**
1. Go to Guibuilder
2. create new project
3. add TextInput/NumberInput/ Text 
4. change Height and width.
5. Move the Element to different position.

**Expected behavior**
the Height width changed back to default value.

**Crash log / Project files**
no crash.

**Screenshots**
1. 
<a href="https://ibb.co/d6yjTwv"><img src="https://i.ibb.co/BjRcp5J/Gui1.png" alt="Gui1" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>upload</a><br />

2. 
<a href="https://ibb.co/MPL90qC"><img src="https://i.ibb.co/BTRwM8C/Gui2.png" alt="Gui2" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>upload</a><br />

**Version**
- Builder version: 0.17.b02
- OS:  Windows

**Additional context**

**Comment by Pconti31** [comment]
@nadjet09 Well, that stinks.  I reproduced the problem.  I'll provide a hotfix once I figure out what is going on.
Paul--

**Comment by Pconti31** [comment]
@nadjet09 HotFix 0.17.b06 addresses this problem.
Paul--

**Comment by nadjet09** [comment]
it's working for me :)
