### ISSUE TITLE
Request: Scroll bar set width and thumb size in textbox and listbox

### ISSUE THREAD

**Issue by nadjet09** [ImpulseAdventure/GUIslice-Builder#194]
**Describe the solution you'd like**
scroll bar in textbox and listbox need to be able to be edited too. 

**Additional context**
Scroll bar is bit narrow to be picked by touch when using finger, and need a pointy tool.
when creating a listbox or textbox the scroll bar width and thumb sizes are small and and hard to pick with finger, so sometimes need to remove the scroll bar and add a slider or seeker, but since the scrollbar is there it can be edited as the seeker or the slider too.

example:
<a href="https://ibb.co/yRrfCc0"><img src="https://i.ibb.co/N3MVqdx/scroll.png" alt="scroll" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>pic uploader</a><br />

**Comment by Pconti31** [comment]
@nadjet09 Seems reasonable.  I'll take a look.
Paul--

**Comment by Pconti31** [comment]
@nadjet09 This will be in Release 0.17.b07
Paul--
