### ISSUE TITLE
Builder 4K Resolution Support

### ISSUE THREAD

**Issue by aminhusni** [ImpulseAdventure/GUIslice-Builder#202]
The builder sofware does not show well on 4K monitor. Some of the menus are cropped and inaccessible. 

Open software in 4K monitor. 

<img width="1919" alt="2022-05-02 21_55_03-" src="https://user-images.githubusercontent.com/8511047/166246111-da63623e-347c-437a-b20d-7b7e26c7bb19.png">

**Version**
- Builder version: 0.17.b11
- OS: Windows 11 Version 21H2 (OS Build 22000.613)

**Comment by Pconti31** [comment]
Hopefully fixed in release 17.b12.  Note scaling of icon will look poor.  looking at new icons that can scale up for a future release.
