### ISSUE TITLE
Resolution changes to 240*320 without request.

### ISSUE THREAD

**Issue by BitsMonger** [ImpulseAdventure/GUIslice-Builder#204]
**Describe the bug**
- if  change text color or toggle button color(maybe the same with rest of elements).
- if put computer to sleep and after wakeup the computer to carry on the work and GuiBuilder still open.
= so with those last two that conditions  I've encountered,  the display resolution goes back to 240x320 voluntarily, while I'm working on 320x480,(this probably started after the scale feature was added)
**To Reproduce**
1-start project with 320x480 resolution
2-chnage text elemt color, frame color, or fill color

**Expected behavior**
Eproject_options resolution should change to 240x320

**Screenshots**
this was after wake up PC from sleep mode.

<a href="https://ibb.co/BnRQFrL"><img src="https://i.ibb.co/tL5vFxB/resolution-crash2022-05-04-122806.jpg" alt="resolution-crash2022-05-04-122806" border="0"></a>

**Version**
- Builder version: 0.17.b11
- OS: Windows 10

**Comment by Pconti31** [comment]
@nadjet09 Yes, I discovered this bug myself when working on a new project using 17b11.  It is very annoying. Seems I got too clever with some of optimizations I put in to support scaling.  I have fixed it in b12 but that is still a few weeks away from release.  

You can work around this by making the Edit->Options->General tab display width and height the same as your current project E_PROJECT_OPTIONS tab display width and height.

Paul--

**Comment by nadjet09** [comment]
Great, thanks for the trick 👍

**Comment by Pconti31** [comment]
fixed in release 17.b12
