### ISSUE TITLE
permission denied error when running .sh on Ubuntu 22.04

### ISSUE THREAD

**Issue by joshbrown75** [ImpulseAdventure/GUIslice-Builder#212]
I'm running Ubuntu Desktop 22.04, default install (no upgrades other than those that come with the installer).  I downloaded the builder-linux-x64-0.17.b12.tgz file and was able to tar extract the archive as per the instructions; however, when I got to the part where it says "run ./GUIslice.sh" I get a permission denied error even when running with the sudo command.  Not sure where to go from here._

I'm new to the linux environment, is there a switch I need to flip somewhere to let me run the .sh command?

**Comment by Pconti31** [comment]
@joshbrown75 Try this inside your terminal
```
sudo chmod +x GUIislice.sh
```
Please post if this works for you.  
Paul--

**Comment by Pconti31** [comment]
@joshbrown75 Since you haven't responded in two weeks I'm going to assume my suggestions worked or you gave up.

In either case I'm going to close this issue.  If you are still having problems and you post any new information I'll reopen.
Paul--

**Comment by Pconti31** [comment]
fixed in release 0.17.b13
