### ISSUE TITLE
Folder loop creation when saving to new location

### ISSUE THREAD

**Issue by raomin** [ImpulseAdventure/GUIslice-Builder#215]
**Describe the bug**
I had issues when saving to a custom location (I'll fill another issue for this), so I tried and successfully saved in the default Documents\Arduino folder.
Then I wanted a better location for my files, so I created a folder named _guislide_, opened it and clicked the Select folder button in the UI.
The program hanged and started to create sub copies of all the folders before _guislide_ from the Arduino folder, recursively...
I killed it before it went too far...

**To Reproduce**
1. Save as, select default location (Arduino).
2. Reopen save as, create a new folder eg _guislice_, open the empty folder and click Select Folder.

**Expected behavior**
New project files are create in the new folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/4460208/199840682-f7e933cf-fcbe-46a2-b551-031f29aa7b3b.png)

**Version**
- Builder version: 0.17b12
- OS: Win10

**Comment by Pconti31** [comment]
@raomin First I have no question there is a bug and a serious one at that.  However I just tried your steps and (many times) and I can't reproduce the issue.   

Can you zip the project you first did a saveas, and list exactly the steps and names you used?.
No chance you have any links inside your project folder?
I notice in your screen shot arduino.ino and arduiono_GSLC.h (weird naming) in a top level folder with many folders under it.
Any chance your saveas project isn't stored in the path you think it is?

If after you zip up your first project (I don't need to compile or run it) and I follow your more detailed steps everything still works for me I can post a debugging version of the Builder for you to try that will log everything to GUIsliceBuilder/logs/builder.log.  
You can then post that file for me so  can see what is going on.  I'll limit the copying of files to say 20 to avoid looping.
Paul--
