### ISSUE TITLE
How I enter Project name in Key area of PROJECT OPTION table ?

### ISSUE THREAD

**Issue by Andy1956** [ImpulseAdventure/GUIslice-Builder#217]

**Comment by Pconti31** [comment]
@Andy1956 Key is a write protected internal variable.  Even if you could change it it would make no sense.  

I'm not really sure what you really want here.
Are you trying to change the name of the project?  If so do a SaveAs from the File menu.  Remember that the Arduino IDE requires the *.ino to have the same name as the folder its inside so siply renaming a project isn't enough, many items need to renamed.  The Builder will do this for you using the SaveAs command.

If you need something else please give a better description of what you need.
Paul--

**Comment by Pconti31** [comment]
@Andy1956 I'm closing this for lack of information.  I'll reopen if you post any further details.
