### ISSUE TITLE
Tree view > Adjust Width Area

### ISSUE THREAD

**Issue by kellers76** [ImpulseAdventure/GUIslice-Builder#220]
is it possible to adjust the width of the tree view area? 
I have long field names and do not see everything or can not currently adjust the width

**Comment by Pconti31** [comment]
@kellers76 Turns out I finally figured out how to support users dynamically dragging the TreeView panel to resize.  The size will be stored so the next time you open the Builder the TreeView will be the size you created.
This will be in Release 0.17.b16
Sometime today or tomorrow.

**Comment by Pconti31** [comment]
@kellers76 Should be fixed in Release 0.17.b16.

I would appreciate an acknowledgment whether or not this fixes your issue.  If so, adding a star would be nice.
Paul--

**Comment by Pconti31** [comment]
fixed Release 0.17.b16
