### ISSUE TITLE
Area simulates TFT panel > scroll possibility with a large number of pages

### ISSUE THREAD

**Issue by kellers76** [ImpulseAdventure/GUIslice-Builder#221]
I have a lot of individual pages in my project, so the current selection option among each other is not enough. 
Is it possible to see a scroll bar here?

**Comment by Pconti31** [comment]
@kellers76 It's already at the top when you have more than a few pages.
![TFT_SCROLLBAR](https://user-images.githubusercontent.com/44075106/203066954-b483dc3c-adba-472c-bf98-4f857a62086f.png)
One thing I was thinking of adding in a future release is to add [+] [-] to pages listed in  the tree view so users can expand or collapse pages when they want to see elements on a page inside the tree view.
Paul--

**Comment by Pconti31** [comment]
@kellers76 One other thing that may not be obvious.  In the tree view you can double click on a PAGE and it will collapse the elements even though no [+-] icon is present.  You can therefore collapse all of your 48 pages and and they will automatically open up when you select an element inside the TFT simulation screen.

**Comment by Pconti31** [comment]
@kellers76 Release 0.17.b16 The TreeView will support selecting the icons for Expand and Collapse Page Elements. 
Inside the TreeView Pages will start out collapsed to better support larger projects.
Paul--

**Comment by Pconti31** [comment]
Since no further communication I'll assume this is fixed.
