### ISSUE TITLE
SdFat? Possible?

### ISSUE THREAD

**Issue by tbillion** [ImpulseAdventure/GUIslice-Builder#237]
I realize we all get busy i was looking through the code the other day and was wondering when if you had time we could possibly get sdfat support becasue it will not compile on RPI 2040 without this due to the following errors:

```
In file included from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.1.1\libraries\SDFS\src/SDFS.h:35,
                 from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.1.1\libraries\SD\src/SD.h:24,
                 from C:\Users\LocalAdmin\Documents\Arduino\libraries\GUIslice\src\GUIslice_drv_tft_espi.cpp:87:
C:\Users\LocalAdmin\Documents\Arduino\libraries\SdFat\src/SdFat.h:448:2: warning: #warning File not defined because __has_include(FS.h) [-Wcpp]
  448 | #warning File not defined because __has_include(FS.h)
      |  ^~~~~~~
In file included from C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.1.1\libraries\SD\src/SD.h:24,
                 from C:\Users\LocalAdmin\Documents\Arduino\libraries\GUIslice\src\GUIslice_drv_tft_espi.cpp:87:
C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.1.1\libraries\SDFS\src/SDFS.h: In member function 'virtual int sdfs::SDFSFileImpl::availableForWrite()':
C:\Users\LocalAdmin\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.1.1\libraries\SDFS\src/SDFS.h:279:31: error: 'using element_type = class File32' {aka 'class File32'} has no member named 'availableSpaceForWrite'; did you mean 'availableForWrite'?
  279 |         return _opened ? _fd->availableSpaceForWrite() : 0;
      |                               ^~~~~~~~~~~~~~~~~~~~~~
      |                               availableForWrite
Multiple libraries were found for "SdFat.h"
```

i use the earle philhower core for the rp2040. For clarification all of the code works until you get into the adding images part which is non functional. 

I would be happy to implement the changes needed, but i may need a bit of guidance as to where all the places for SD.h are integrated, i took a precursory look and noticed you already included a switch flag for sdfat but it hasn't been implemented.

Thanks!

**Comment by Pconti31** [comment]
Please Note, I wrote and try to support The GUIsliceBuilder.  @ImpulseAdventure Calvin wrote and supports the API which is what you want to modify but since his work-load has prevented him from doing much support I'll try and answer any questions I can if you continue on to try and modify the API to use SDFat.  Just ask any questions here.

Paul--

**Comment by Pconti31** [comment]
@tbillion Its been a couple of weeks and no further communication from you so I'm going to close this issue.
I'll reopen if you ask any questions.
