### ISSUE TITLE
An Error!

### ISSUE THREAD

**Issue by MRcode2102** [ImpulseAdventure/GUIslice-Builder#243]
Hello my friend
are you OK?
I got an output in my project after finishing the design part UI
Then I got an output from the code inside your program GUIslice-Builder
But while compiling by Arduino IDE software, the output codes gave me the following error
And I think the problem is with your library
can you help me dear
Thank you for your kindness

the error code :

`
C:\Users\mrcod\Desktop\coolerProject\cooler\cooler_main_proj\cooler_main_proj.ino: In function 'bool CbKeypad(void*, void*, int16_t, void*)':
cooler_main_proj:88:27: error: 'gslc_ElemXKeyPadDataTargetIdGet' was not declared in this scope
   int16_t nTargetElemId = gslc_ElemXKeyPadDataTargetIdGet(pGui, pvData);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cooler_main_proj:89:17: error: 'XKEYPAD_CB_STATE_DONE' was not declared in this scope
   if (nState == XKEYPAD_CB_STATE_DONE) {
                 ^~~~~~~~~~~~~~~~~~~~~
cooler_main_proj:96:12: error: 'E_ELEM_TEXTINPUT1' was not declared in this scope
       case E_ELEM_TEXTINPUT1:
            ^~~~~~~~~~~~~~~~~
C:\Users\mrcod\Desktop\coolerProject\cooler\cooler_main_proj\cooler_main_proj.ino:96:12: note: suggested alternative: 'E_ELEM_TEXT11'
       case E_ELEM_TEXTINPUT1:
            ^~~~~~~~~~~~~~~~~
            E_ELEM_TEXT11
cooler_main_proj:97:40: error: 'm_pElemInTxt1' was not declared in this scope
         gslc_ElemXKeyPadInputGet(pGui, m_pElemInTxt1, pvData);
                                        ^~~~~~~~~~~~~
C:\Users\mrcod\Desktop\coolerProject\cooler\cooler_main_proj\cooler_main_proj.ino:97:40: note: suggested alternative: 'm_pElemBtn1'
         gslc_ElemXKeyPadInputGet(pGui, m_pElemInTxt1, pvData);
                                        ^~~~~~~~~~~~~
                                        m_pElemBtn1
cooler_main_proj:97:9: error: 'gslc_ElemXKeyPadInputGet' was not declared in this scope
         gslc_ElemXKeyPadInputGet(pGui, m_pElemInTxt1, pvData);
         ^~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\mrcod\Desktop\coolerProject\cooler\cooler_main_proj\cooler_main_proj.ino:97:9: note: suggested alternative: 'gslc_ElemXSeekbarCreate'
         gslc_ElemXKeyPadInputGet(pGui, m_pElemInTxt1, pvData);
         ^~~~~~~~~~~~~~~~~~~~~~~~
         gslc_ElemXSeekbarCreate
cooler_main_proj:105:24: error: 'XKEYPAD_CB_STATE_CANCEL' was not declared in this scope
   } else if (nState == XKEYPAD_CB_STATE_CANCEL) {
                        ^~~~~~~~~~~~~~~~~~~~~~~
Multiple libraries were found for "SD.h"
 Used: C:\Users\mrcod\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.13\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
 Not used: C:\Users\mrcod\Documents\Arduino\libraries\SD
exit status 1
'gslc_ElemXKeyPadDataTargetIdGet' was not declared in this scope
`

GuiSlice-Builder Version: 0.17.b24
GuiSlice Version: v0.17.0
My driver: esp-tftespi-default-xpt2046.h

and this is my .ino Generated output with your program + Designed UI + data folder:

for icons design i using GUIslice_Image2c version: 2.03

**Comment by Pconti31** [comment]
@MRcode2102 Seems you once had an input text element called "m_pElemInTxt1" which you must have deleted along the way of finishing your app.   The builder hoever can't handle such a condition.
This is similar to [Issue 47](https://github.com/ImpulseAdventure/GUIslice-Builder/issues/47).
Attached is a repaired version of your app. 
[cooler_main_proj.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/12792633/cooler_main_proj.zip)
 I hope this helps.
Paul--

**Comment by MRcode2102** [comment]
I thank you very much dear
The previous problem and error has been fixed
Just now I encountered another error and I don't know exactly how to fix it
These pictures used in Designed UI should be called from where?
According to this part of the settings in your program, which option should I choose and then where should I put the **Artboard .c** format photo files?

the error:

`c:/users/mrcod/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\cooler_main_proj.ino.cpp.o:(.literal._Z16InitGUIslice_genv$part$3+0x3c): undefined reference to `Artboard_1'
c:/users/mrcod/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\cooler_main_proj.ino.cpp.o:(.literal._Z16InitGUIslice_genv$part$3+0x44): undefined reference to `Artboard_2'
c:/users/mrcod/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\cooler_main_proj.ino.cpp.o:(.literal._Z16InitGUIslice_genv$part$3+0x48): undefined reference to `Artboard_3'
c:/users/mrcod/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\cooler_main_proj.ino.cpp.o:(.literal._Z16InitGUIslice_genv$part$3+0x4c): undefined reference to `Artboard_4'
c:/users/mrcod/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\cooler_main_proj.ino.cpp.o:(.literal._Z16InitGUIslice_genv$part$3+0x50): undefined reference to `Artboard_5'
collect2.exe: error: ld returned 1 exit status
Multiple libraries were found for "SD.h"
 Used: C:\Users\mrcod\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.13\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
 Not used: C:\Users\mrcod\Documents\Arduino\libraries\SD
exit status 1
Error compiling for board Adafruit ESP32 Feather.
`

the Program's Screenshot:

![PR](https://github.com/ImpulseAdventure/GUIslice-Builder/assets/81368626/913dcc25-10cd-4653-8210-cef8a1698308)

the Program with Deps...

[cooler_main_proj_new.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/12793669/cooler_main_proj_new.zip)

**Comment by MRcode2102** [comment]
wow, it works fine !
thank you, MR 
you are a very great man.
