### ISSUE TITLE
How to set create modifiable text label ?

### ISSUE THREAD

**Issue by eagl1** [ImpulseAdventure/GUIslice-Builder#270]
``Hi,

I want a number output text window, I couldn't find it on the builder set of tool.

I found this in the calculator example, but I don't know how to do it automatically without copying it from a source code.

```
  // Create E_TXT_RESULT modifiable text label
  static char m_strResult[11] = "";
  pElemRef = gslc_ElemCreateTxt(&m_gui, E_TXT_RESULT, E_PG_MAIN, (gslc_tsRect) { 150, 200, 62, 12 },
    (char*)m_strResult, 11, E_FONT_TXT1);
  gslc_ElemSetTxtCol(&m_gui, pElemRef, GSLC_COL_GREEN);
  m_pElemResult = pElemRef; // Save for later
```

My question is how to do it from the gui builder ? and would the code be set automatically ? or I have to copy these lines of code ?

**Comment by Pconti31** [comment]
@eagl1 You should read the faq.pdf under topic
**Can you change a Text String at runtime?**
Paul--

**Comment by eagl1** [comment]
Where can I find the file ?

**Comment by Pconti31** [comment]
@eagl1 Yes, that will work.  However, the pdf file is available as one of the downloads along side of the release, FAQ.pdf and the user_guide.pdf
Paul--

**Comment by eagl1** [comment]
Hi,

I'm checking the example:
`E:\Programs_Files\Arduino\libraries\GUIslice-master\examples\arduino\ex06_ard_callback\ex06_ard_callback.ino`

But it's difficult for me to understand the most important tools to run the task of writing changing numbers on the display.

Can you provide me with the main steps to develop a simple counter that counts; e.g. every 100ms, on the display ?

**Comment by Pconti31** [comment]
@eagl1 Here you go...

[simple-counter.zip](https://github.com/user-attachments/files/17269401/simple-counter.zip)

Paul--

**Comment by eagl1** [comment]
OK, I got it. I must set an external storage for the text to be done in the RAM. Otherwise, it will be set as a constant and the data will be saved in the flash.

![image](https://github.com/user-attachments/assets/1eb60548-8aa8-461e-87c1-10c10e6616f4)


How did you made the number in the middle of the text area in point number 2 ?

**Comment by eagl1** [comment]
Also, what is the size of the external storage ? is it in bytes or digits ?

**Comment by Pconti31** [comment]
@eagl1 size of the external storage is it in bytes not digits.
No difference unless you are using unicode instead of asci characters.

**Comment by eagl1** [comment]
I've done it, thank you so much as always :)

This is 7-servos tune code, as a start for our robot arm control.
[robot_arm_project.zip](https://github.com/user-attachments/files/17272470/robot_arm_project.zip)
