### ISSUE TITLE
Create C-array from Selected Image file for BtnImg upon Generating Code w/ Image Extern

### ISSUE THREAD

**Issue by Adr-hyng** [ImpulseAdventure/GUIslice-Builder#276]
Thanks for making this useful and awesome project, it helped me a ton, and really wanted to contribute by suggesting a feature that is already been solved by your other tool, namely the Image2C. However, could be awesome if it's built-in with the builder itself.

Context:
![image](https://github.com/user-attachments/assets/cfcdfaca-eaef-4e84-8df7-68b19d211479)

P.S I'm not an expert dev, but I would love to contribute to this project, if i have the time.

**Comment by Pconti31** [comment]
Thanks for you kind words and your suggestion.  I'll take it under advisement for a future release.
You don't need to be an expert to contribute to this project.
Feel free to contact me on my public email p_conti@hotmail.com if you need any pointers.
Paul--
