### ISSUE TITLE
Missing Template: <FONT_TFT_ESPI>

### ISSUE THREAD

**Issue by Bwanna** [ImpulseAdventure/GUIslice-Builder#38]
**Describe the bug**
When Generating Code for a New Project based on Target Platform -Arduino TFT_eSPI, produces an Error Msg: "Code Generation Failed: builder.codege.CodeGenException: Missing template: <FONT_TFT_ESPI>"

**To Reproduce**
1. INSTALL and RUN - GUIslice Builder ver: 0.13.b006
2. Open "Options" (under EDIT Menu)
3. SELECT "Arduino TFT_eSPI( under TARGET PLATFORM)  ([OK}
4. ADD TEXT BOX to project Simulated Panel
5. SAVE Project (any name will do)
5. SELECT "CODE GENERATION" 
   Three ways to do this:
    1. CTRL+G
    2. Select FILE | CODE GENERATION
    3. Select Code Generation BUTTON located in upper menu banner

**Expected behavior**
Expect "*.ino" file to be created with appropriate reference to TFT_eSPI.h

**Version**
- Builder version: GUIslice Builder ver: 0.13.b006
- OS: Windows

**Comment by Pconti31** [comment]
Assigned bug number 117 and fixed in release 0.13.b007

The template is inside the arduino.t template file but the system was incorrectly looking inside linux.t file.

Paul--
