### ISSUE TITLE
TFT-eSPI: Error with Font APIs

### ISSUE THREAD

**Issue by Bwanna** [ImpulseAdventure/GUIslice-Builder#40]
**Describe the bug**
Selecting Target Platform: Arduino TFT_eSPI, Font files automatically added to "Fonts !Start! in the sketch result in error messages

**To Reproduce**
1. Create a NEW Test Project within GUISlice 
2. Select "Arduino TFT-eSPI" as the Target Platform
3. Add an Element and Select of FreeFont for that Element
4. Generate Code (for Sketch)

**Expected behavior**
Expect Fonts to load properly

**Version**
- Builder version:  GUIslice Builder ver: 0.13.b007
- OS: Windows

**Additional context**
-The GUI Builder correctly includes "TFT_eSPI.h" in the sketch.
-The TFT_eSPI.h API automatically references the location of the FreeFonts within its directories e.g. 'fonts/gfxff'
NO ERRORS occur if I comment out all "#include "Fonts/....."
RECOMMENDATION:  Do not include Fonts when selecting "TFT-eSPI" as the target platform, since the font location within that API is already identified.

**Comment by Pconti31** [comment]
Thank you for the report.  Assigned bug number 118.

Paul--

**Comment by Bwanna** [comment]
You're welcome. I might have another one, but I need to verify it's not my
error in setting up the Options.

**Comment by Pconti31** [comment]
Ok, I'll hold up the update for a few days to see if you have another bug.

Paul--

**Comment by Bwanna** [comment]
Paul, didn't mean to hold you up closing this.  I'll submit a separate bug report for anything else I find.  Thanks!
