### ISSUE TITLE
Set Ring Gauge text

### ISSUE THREAD

**Issue by dbonnell** [ImpulseAdventure/GUIslice-Builder#42]
**Describe the solution you'd like**
The builder shows text of the `<<Starting Value>>%` but the generated code and there is no way to change this.  If the gauge isn't being used to show a percentage, this isn't always appropriate.  There should be a way to specify the text displayed in the center of the gauge.

**Additional context**
The generated code always defines an empty string for the gauge text, which is different to what you see in the builder.  For example:
```static char m_sRingText1[11] = "";```

**Comment by Pconti31** [comment]
Thanks for the info.  Assigned bug no. 120.
Paul--

**Comment by Pconti31** [comment]
Kind of a gray area here.  Builder doesn't actually set the text the user must do so say inside loop() each cycle.  Using say:
```
  // Update the XRingGauge text string with a percentage
  snprintf(acStr, 10, "%d%%", m_nSliderPos);
  gslc_ElemSetTxtStr(&m_gui, m_pElemXRingGauge1, acStr);
```
So you can just instead do:
```
gslc_ElemSetTxtStr(&m_gui, m_pElemXRingGauge1, "My Text");
```
The storage is already large enough for most text.  Next release could add another property just for text but would this make it more confusing for new users? 
Paul--

**Comment by dbonnell** [comment]
Hi Paul,

That's a fair point.  I guess I was just expecting the generated code to produce the same output as I saw in the builder, but it didn't quite.

Rather than exposing the text itself, what if when the minimum and maximum in the builder are 0 and 100, respectively, the generator simply emits one extra line of code (line 3 below), to initialize the starting text value, to be the the same as what the builder shows?

For example:
```
  // Create ring gauge E_ELEM_RINGGAUGE1 
  static char m_sRingText1[11] = "";
  snprintf(m_sRingText1, 11, "%d%%", 93); // Set initial text  <= NEW GENERATOR CODE
  pElemRef = gslc_ElemXRingGaugeCreate(&m_gui,E_ELEM_RINGGAUGE1,E_PG_MAIN,&m_sXRingGauge1,
          (gslc_tsRect){25,60,100,100},
          (char*)m_sRingText1,11,E_FONT_TXT10);
  ..
```

**Comment by Pconti31** [comment]
Sounds like a good idea to me. I'll fix it in the next release.
Paul--

**Comment by Pconti31** [comment]
I have talked this over with Calvin and we have decided that it's best to remove showing the percent in the TFT Simulation.  People see what they get without any preconceived notions for runtime.
The more straightforward / intuitive the better usually for everyone.  

This will appear in build 0.13.b009
Paul--
