### ISSUE TITLE
Error to change Grahic object

### ISSUE THREAD

**Issue by arnold-b** [ImpulseAdventure/GUIslice-Builder#44]
[test.zip](https://github.com/ImpulseAdventure/GUIslice/files/3989284/test.zip)

Hello, 

i just made one sample and i try to Change the Colors. I can select the object, but i can not change it. Everytime another object will be change. 

Please try to change the Button with the label todo. 

Thanks

**Comment by Pconti31** [comment]
Hmmm, Might be a bug with copy.  I'll test it further but seems to be working ok with
Builder version 0.13.b009 so if you were using an older version please upgrade.

You can help yourself make repairs and report bugs I can fix by doing saves of your project as you
go along creating new elements.  

Each time you do a save I create backup copies of your project the latest being _projectname_.prj.bak. 

Then once you have done more than one saves gui_backup folder is created and  _projectname_.prj.##N is created where N begins at 1 and increases
as you do more saves.  

Thus the latest save point is always  _projectname_.prj.bak and the next save point is  gui_backup\_projectname_.prj.##N where N is the largest number. You can then copy and rename them to your project file name to recover to a save point.

For example, finding out a project "test.prj" is damaged you can go back to a working save point by -- first doing a zip file of the full folder.(So you can recover and report a bug)
- find test.prj.bak.  
- delete test.prj, 
- rename test.prj.bak to test.prj 

and you have restored yourself to the lastest save point. 

If that doesn't work you go into gui_backup and find the latest test.prj.##N
file and do the same to it.  looping until you get a working project file.

Also, please pass all files to me so I can try and fix the problem for you and other people.
Reporting builder version, and target platform.

AS to how I fixed your project.  No magic tool involved. I simply deleted the problem UI elements,
L6 which also deleted todo text button, deleted L7 and L8 which also seemed problematic, then
copied elements L2, L3, and L4 and pasted, moved them into L6,L7,L8 positions and renamed them. 
Then created a new todo text button and did a save.

AS to the Base page thing I explained it in a poor way.  A base page contains any UI elements meant to be common to all pages, Main and Extra pages. 
On each refresh of a display, First a Base page is written to screen, then Main or Current page is written on top of it.  So hopefully you can see why your placing all ui elements on the base page isn't right.
Paul--

**Comment by arnold-b** [comment]
OK. Thank you. 
I´m using your current Version
