### ISSUE TITLE
Incorrecct visual width for ListBox without scrollbar in builder

### ISSUE THREAD

**Issue by knyipab** [ImpulseAdventure/GUIslice-Builder#51]
When a listbox is created with option "Add Scrollbar?" turned off, the listbox's visual width doesn't match with the actual width when being rendered by Arduino. 

For example, open this project and the listbox in builder just fit the screen. But after upload to Arduino, the box is obviously off the screen. 
[gui2.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4013848/gui2.zip)

I think the builder still "reserve some space for the non-existing scrollbar" but that's not the case when rendered by GUIslice. 

Version: 13.0.b010 on Windows. Platform: ESP32 (Arduino core).

**Comment by knyipab** [comment]
I just found that it's not just width, but also height mismatch. The builder is actually reserving space for scrollbar **and margin**.

**Comment by Pconti31** [comment]
Assigned bug 127.   I don't actually try and calculate the box size to hold lists.
Calvin has never given me formula for doing so.   However, my bug here is that when doing the display I'm subtracting 23 from the box width and 7 from the box height to account for the missing scrollbar during display but not changing the actual property width and height.  Without a formula for determining proper height and width of your lists users are forced to use trial and error to size lists.   All I can do is show box size.   My bug fix may simply be me no longer subtracting 23 and 7 from width and height during display.
Paul--

**Comment by Pconti31** [comment]
fixed in release 0.13.b011
