### ISSUE TITLE
Move up/down buttons for ListBox items

### ISSUE THREAD

**Issue by knyipab** [ImpulseAdventure/GUIslice-Builder#55]
After I added items into a listbox, I couldn't reorder the items in builder, so I delete all of them and add them again 😀😂. Having two more buttons (move up ↑ and move down ↓) should make it handy. It's quite a basic feature for listbox editor😉.

**Comment by Pconti31** [comment]
You can reorder by simply selecting the item and dragging it to a new position.
I'll keep you suggestion of move up and down as a enhancement for a future release.
Paul--

**Comment by Pconti31** [comment]
fixed in release 0.13.b011
