### ISSUE TITLE
In some themes, the app window is not controllable

### ISSUE THREAD

**Issue by tddpirate** [ImpulseAdventure/GUIslice-Builder#59]
**Describe the bug**
After setting the application to work with a theme, the application's look changes accordingly. However, for themes Nimbus, CDE/Motif, GTK+:
- Top right window control buttons (minimize/maximize/close) do not appear.
- It is impossible to resize or drag the window.

Theme Metal is working OK:
- The top right window control buttons appear and work as expected.
- It is possible to resize or drag the window.

Since File/Exit works in all cases, the application is usable as is.
Therefore, I believe that this bug is cosmetic.

**To Reproduce**
1. Start the application as usual (using `./GUIslice.sh` or clicking on its icon).
2. Select `Edit`/`Options` and ensure that you on the `General` tab.
3. Select a theme from the provided list of themes.
4. Dismiss the Edit Preferences dialog by clicking on `OK` button.

**Expected behavior**
The theme changes to the chosen one. Regardless of chosen theme, you see Minimize/Maximize/Close buttons on the top right corner of the window.
It is also possible to drag or resize the window using mouse drags as usual for the xfce4 desktop.

**Version**
- Builder version: 0.13.b012
- OS: Linux - Debian Buster, xfce4 desktop

**Comment by Pconti31** [comment]
Seems the title bar is missing in some themes.
Assigned bug 133.
Paul--

**Comment by Pconti31** [comment]
Found the problem.
Fixed in 0.13.b014
