### ISSUE TITLE
Number Input ERROR: GetXDataFromRef(Type 4116, Line 254) Elem type mismatch

### ISSUE THREAD

**Issue by rotus8** [ImpulseAdventure/GUIslice-Builder#60]
I have identified two problems with the Number Input widget.

1) The arduino generated sketch creates a keypad element that declares the routine bool CbKeypad, but does not include a return statement.

Compile fails with
exit status 1
no return statement in function returning non-void [-Werror=return-type]

2) Fixing the above then gives runtime errors:
In the Common Button Callback the statement:
   gslc_ElemXKeyPadTargetIdSet(&m_gui, m_pElemFoobar, E_ELEM_NUMINPUT1);
gives the error:
    ERROR: GetXDataFromRef(Type 4116, Line 283) Elem type mismatch
then the statement
  gslc_ElemXKeyPadValSet(&m_gui, m_pElemFoobar, gslc_ElemGetTxtStr(&m_gui, m_pElemFoobar));
gives the error:
   ERROR: GetXDataFromRef(Type 4116, Line 254) Elem type mismatch

Here are my files:
[NumInputTest.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4074184/NumInputTest.zip)

Builder 0.13.b012, arduino 1.8.10, Windows 10

**Comment by Pconti31** [comment]
I'll add the return statement in the next build 0.13.b013
but it compiles fine without it using arduino's ide.
The Elem type mismatch I'm passing off to Calvin since its a GUIslice api error code.
I'll fix whatever he finds in the code gen once he identifies it.
Paul--

**Comment by ImpulseAdventure** [comment]
Hi @rotus8 -- thanks for the report!

The second error "Elem type mismatch" is indicating that the wrong GUI element was passed into the `gslc_ElemXKeyPadTargetIdSet()` and `gslc_ElemXKeyPadValSet()` APIs. These APIs require a keypad element reference to be passed in, but instead it looks like the numeric field was supplied instead.

In the attached code "NumInputTest", I think we would want the Builder to provide `m_pElemKeyPad` in place of `m_pElemFoobar`.

**Comment by Pconti31** [comment]
Assigned bug 136 and fixed in Release 0.13.b013
Paul--
