### ISSUE TITLE
TextBox font problem

### ISSUE THREAD

**Issue by rotus8** [ImpulseAdventure/GUIslice-Builder#62]
**Describe the bug**
The font of the text in a textBox gets the wrong font selected. Apparently it is affected by the font selection of other elements. Specifically can be demonstrated in the ex_10_textbox example by changing the font of the quit button to a non-builtin font.

**To Reproduce**
1. Open the ex10_bld_textbox example in builder.
2. Generate the .ino, edit as in the example .ino file
3. Upload to target. Text in textbox is good.
4. In builder change the font of the quit button to one of the non-bultin fonts.
5. Generate the .ino file
6. Upload to target. Text in textbox starts out fine, but when the counter starts the wrong
   font is used.

**Expected behavior**
Font of the text in textBox should not be affected by the font in other elements.

**Crash log / Project files**
Starting point, works.
[textBoxTest.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4099714/textBoxTest.zip)
Modified font of Quit button, shows failure.
[textBoxTestFontError.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4099720/textBoxTestFontError.zip)

**Screenshots**

**Version**
- Builder version:  0.13.b013
Arduino 1.8.10
GUIslice 0.13.0

- OS: [e.g. Windows, LINUX, Mac OS] Windows 10

**Additional context**

**Comment by Pconti31** [comment]
Sorry, but i'm retired and living on social security so I can't afford all of the boards and displays Calvin supports.   I ran your tests on my arduino mega and adafruit 2.8 tft.  It ran fine in both cases.
As far as I can see the code generation is correct so I suspect it's a problem with GUIslice api.
I'll pass this along to Cal and see what he says.  If it is a problem with the Builder I'll fix it.
Paul--

**Comment by rotus8** [comment]
Thanks! I completely understand that it is very difficult to test every possible platform. I really appreciate the work you have done, it is super useful. If the fix is not straightforward I can probably figure out a workaround. I really need a tiny font for my log window. 

Thank you for the rapid response. 

⁣Ted​


-------- Original Message --------

**Comment by ImpulseAdventure** [comment]
Hi Ted --

I have tried recreating the scenario you reported on my ESP32 Adafruit Feather but have not observed the same issue.

Is there any chance you might be able to capture a short video clip of what you see on the display and attach it to this ticket? It seems a bit surprising to me that the sample code would cause the font to change during runtime unless perhaps there was a memory corruption event.

When you load the "textBoxTestFontError" generated code into a fresh Arduino IDE instance, do you still observe the same problem (ie. is it easily reproducible on your end?)

What MCU device (ATmega, ESP32, etc.) and which GUIslice config file are you using in your environment?

many thanks!

**Comment by Pconti31** [comment]
Due to lack of activity I'm going to close this issue for now.
If you come up with more information feel free to re-open.
Paul--

**Comment by rotus8** [comment]
Well, there may be a lack of activity, but the
        problem is still there. The example I posted using the builder
        example on a ESP32 shows the problem. I have a hack on my system
        to work for now so I won't push it. I am not sure what
        additional information I can supply, if you can suggest
        something I can try.
      
    Thank you for your efforts though, you have
        allowed me to make a great application. I am most grateful.
      
    Ted
    
    On 2/9/2020 12:26 PM, Paul Conti wrote:
    
    
      
      Due to lack of activity I'm going to close this issue for now.
        If you come up with more information feel free to re-open.
        Paul--
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ImpulseAdventure/GUIslice-Builder/issues/62?email_source=notifications\u0026email_token=ALMK4WE6BEW7WFK3NN2O4OLRCBRITA5CNFSM4KKL2YHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGXC7Q#issuecomment-583889278",
"url": "https://github.com/ImpulseAdventure/GUIslice-Builder/issues/62?email_source=notifications\u0026email_token=ALMK4WE6BEW7WFK3NN2O4OLRCBRITA5CNFSM4KKL2YHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGXC7Q#issuecomment-583889278",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Pconti31** [comment]
Ted:
First I'm very happy you have a work-around and that you have found our project useful.
As to what else you could provide simply answer Calvin's questions.

What is the exact hardware MCU and Display you are using?
Which GUIslice config file are you using?
When you load the "textBoxTestFontError" generated code into a fresh Arduino IDE instance, do you still observe the same problem?
Can you make a video of textBoxTestFontError.ino running and post it?
Can you post your work-around modifications to textBoxTestFontError.ino?

Its clearly a memory corruption problem but the sample you gave runs fine for us so these
answers are needed to go further.
Paul--

**Comment by rotus8** [comment]
I am using an Adafruit HUZZAH32 ESP32 Feather Board (https://www.adafruit.com/product/3405) with an Adafruit TFT FeatherWing - 3.5" 480x320 Touchscreen (https://www.adafruit.com/product/3651).

I am using the esp-tftespi-default-stmpe610.h config file, only modified with touch screen calibration.

The test sketch shows the error from a fresh build, I will attempt to upload the short video I made showing the problem.
https://www.dropbox.com/s/3yqcmrz5ws76z4p/VID_20200212_144654.mp4?dl=0

I would post my application, but it is quite large, it has eight screen pages plus several popups, more than 3000 lines of code. The difficulty I had is on a logging page which required a maximum size textBox with a tiny font, I used BuiltIn(1x)->5x8pt7b. My "workaround" (I would really call it a hack) is to use only BuiltIn fonts for all the elements on the page, it has an EXIT button plus I added two dummy text elements before and after the textBox which use the same 1x font. I also had to change the project default background color to what I used for the textBox fill color because sometimes the default color would be used.

I have ordered an extra display and MCU board that I would be happy to send to you if it would be useful.

Ted

**Comment by Pconti31** [comment]
Hmmm,  I thought this config was the one Calvin tested with.

In looking over your answers for software versions you show
GUIslice 0.13.0 but I assume that's not the real version.
What is the version number inside GUIslice/src/GUIslice_version.h?
The lastest being GUISLICE_VER "0.13.0.16"
No version is given for TFT_espi the lastest being 1.4.20 is that what you are using?

One remaining thing would be your TFT_espi User_Setup.h and the your actual
esp-tftespi-default-stmpe610.h file if you made any edits to it.
If you could zip those up hopefully Calvin can make some progress.

Thank you for your patience.
Paul--

**Comment by Pconti31** [comment]
Ted:
While we wait for Calvin to get some free time and since memory corruption seems an issue I took a closer look at your sample and noticed:
`// Free-running counter for display`
`unsigned  m_nCount = 0;`
this is a 32-bit number for the esp32 not 16 bit.
Your snprintf uses %u not %lu as it should for a 32 bit number.
You could of course change m_nCount to
`uint16_t m_nCount = 0;`
Not sure its your problem but it still should be corrected.
In the meantime I'll take a closer look at XTextbox.<h,c> to see if I notice anything
Further.
Paul--

**Comment by rotus8** [comment]
My installation shows #define GUISLICE_VER "0.13.0" in version.h. I could not get the Arduino library manager to install anything else, so I sideloaded 0.13.0.16. I had some hopes that this would fix it, but the problem persists. I am using TFT_esp 1.4.20.

Here are my setup/config files.
[configStuff.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4201930/configStuff.zip)

Let me know if there is anything else I can do to help. My offer stands to send you an MCU and display if that will help; it is on order, I should have it in a week or so.

**Comment by Pconti31** [comment]
Thanks for the hardware offer and yes, I would need it to hunt down the problem.
You can go to my profile for my public email address.  Send me a message if you still want to send me your hardware and I'll give you my contact information.

I have attached a modified XTextbox.<h,c> that doesn't fix the problem as much as tries to workaround it.  Give it a try.   If it fails just go back to the original versions.
Paul--

[XTextbox.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4204878/XTextbox.zip)

**Comment by rotus8** [comment]
Thanks for the effort, but the new XTextbox
        doesn't change the behavior. The hardware is on order and I will
        be out of town next week. I'll arrange to ship it to you after I
        get back.
    Ted
    
    On 2/14/2020 6:38 AM, Paul Conti wrote:
    
    
      
      Thanks for the hardware offer and yes, I would need it to hunt
        down the problem.
        You can go to my profile for my public email address. Send me a
        message if you still want to send me your hardware and I'll give
        you my contact information.
      I have attached a modified XTextbox.<h,c> that doesn't
        fix the problem as much as tries to workaround it. Give it a
        try. If it fails just go back to the original versions.
        Paul--
      XTextbox.zip
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ImpulseAdventure/GUIslice-Builder/issues/62?email_source=notifications\u0026email_token=ALMK4WHPVUIVNVSYJDLLVALRC2UFLA5CNFSM4KKL2YHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELZHMZY#issuecomment-586315367",
"url": "https://github.com/ImpulseAdventure/GUIslice-Builder/issues/62?email_source=notifications\u0026email_token=ALMK4WHPVUIVNVSYJDLLVALRC2UFLA5CNFSM4KKL2YHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELZHMZY#issuecomment-586315367",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ImpulseAdventure** [comment]
Hi @rotus8 --

I took another look at this issue tonight and think I see a potential source of the problem.
Given that you are using the **Adafruit 3.5" Featherwing** + **Adafruit ESP32 Feather**, we should have the option of two supported library combinations:
- (1) Adafruit_HX8357 + Adafruit-GFX
- (2) TFT_eSPI

**For (2): TFT_eSPI mode:**
- I haven't seen your modified sketch, but does it show an include like the following?
```c++
//<Fonts !Start!>
  #include <Adafruit_GFX.h>
  #include <Fonts/FreeMono9pt7b.h>
//<Fonts !End!>
```
- If so, please check to see that the Builder config setting Edit -> Options -> Target Platform is set for "arduino TFT_eSPI" and not "arduino".
- The TFT_eSPI library has a known incompatibility when run alongside Adafruit-GFX. This was confirmed by Bodmer in https://github.com/ImpulseAdventure/GUIslice/issues/146
- The above Builder setting should cause "TFT_eSPI.h" to be included instead of the Adafruit_GFX and the associated font files, ie: replacing the above with:
```c++
//<Fonts !Start!>
#include "TFT_eSPI.h"
//<Fonts !End!>
```
- If you attempt to run with Adafruit_GFX + TFT_eSPI, you will likely experience memory corruption or other runtime anomalies.

**For (1): Adafruit HX8357 mode:**
- This mode should work properly with the Feather using the following GUIslice config: mult-shld-adafruit_35_feather_touch.h
- To confirm operation with the native Adafruit libraries, please see https://learn.adafruit.com/adafruit-3-5-tft-featherwing/tft-graphics-test

**Comment by Pconti31** [comment]
Cal : Thanks for taking a second look.
I think trying option (1) would be a good idea to try if only to limit the issue to TFT_espi driver
or maybe he can get away without using TFT_espi if the Adafruit drivers work without a problem.

As for (2) no his Builder is correctly configured his app shows:
`//<Fonts !Start!>`
`#if !defined(DRV_DISP_TFT_ESPI)`
 ` #error Builder config "Edit->Options->General->Target Platform" should be "arduino"`
`#endif` 
`#include <TFT_eSPI.h>`
`//<Fonts !End!>`

Assuming option (1) is a no go and the second set of hardware he has on order reproduces  the same issue and that he sends  a set I should be able to determine whats is going on.
Paul--

**Comment by Pconti31** [comment]
Ted:
Thanks to you I was able to find and fix the bug.
It turned out to be inside GUIslice API and not a Builder problem.

If you get a chance please confirm the fixes and I'll close
this issue.
Paul--

[XTextbox-BugFix.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4263908/XTextbox-BugFix.zip)

**Comment by rotus8** [comment]
Great, I'll try it out in the morning. 

Thanks! 

⁣Ted​


-------- Original Message --------

**Comment by rotus8** [comment]
Verified. Works fine, please close.
    Thanks!
      
    Ted
    
    On 2/27/2020 12:22 PM, Paul Conti
      wrote:
    
    
      
      Ted:
        Thanks to you I was able to find and fix the bug.
        It turned out to be inside GUIslice API and not a Builder
        problem.
      If you get a chance please confirm the fixes and I'll close
        this issue.
        Paul--
      XTextbox-BugFix.zip
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ImpulseAdventure/GUIslice-Builder/issues/62?email_source=notifications\u0026email_token=ALMK4WC5BYKAIA5IF6OQRQTRFAOH5A5CNFSM4KKL2YHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENF2CLA#issuecomment-592159020",
"url": "https://github.com/ImpulseAdventure/GUIslice-Builder/issues/62?email_source=notifications\u0026email_token=ALMK4WC5BYKAIA5IF6OQRQTRFAOH5A5CNFSM4KKL2YHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENF2CLA#issuecomment-592159020",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ImpulseAdventure** [comment]
Thanks Ted for the confirmation. I intend to integrate the fix into the library this evening.

**Comment by rotus8** [comment]
Hello Paul,
    I may have spoken too soon. In my full application I find that
      sometimes when I switch to my log page with the text box, the text
      box fill color is not correct, it uses the "default" fill color.
      It corrects itself as soon as text is added to the textbox. The
      text font, size, and color are good.
    
    I have not developed a simple test case yet, perhaps it will be
      obvious. All else seems to be working fine. I can work on a test
      case if the fix is not straightforward.
    Thanks
    
    Ted
    
    On 2/27/2020 12:22 PM, Paul Conti
      wrote:
    
    
      
      Ted:
        Thanks to you I was able to find and fix the bug.
        It turned out to be inside GUIslice API and not a Builder
        problem.
      If you get a chance please confirm the fixes and I'll close
        this issue.
        Paul--
      XTextbox-BugFix.zip
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ImpulseAdventure/GUIslice-Builder/issues/62?email_source=notifications\u0026email_token=ALMK4WC5BYKAIA5IF6OQRQTRFAOH5A5CNFSM4KKL2YHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENF2CLA#issuecomment-592159020",
"url": "https://github.com/ImpulseAdventure/GUIslice-Builder/issues/62?email_source=notifications\u0026email_token=ALMK4WC5BYKAIA5IF6OQRQTRFAOH5A5CNFSM4KKL2YHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENF2CLA#issuecomment-592159020",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Pconti31** [comment]
Yes, A test case would help.
I will look over the code in the meantime.

Could you also open a new issue on the GUIslice github (not the Builder)
It will make things easier for Calvin to track any fixes.

Paul--


________________________________

**Comment by rotus8** [comment]
I have created a fairly simple test case. Opened
        new GUIslice issue #202.
    Ted
    
    On 3/1/2020 1:15 PM, Paul Conti wrote:
    
    
      
      Yes, A test case would help.
      I will look over the code in the meantime.
      
      Could you also open a new issue on the GUIslice github (not the
      Builder)
      It will make things easier for Calvin to track any fixes.
      
      Paul--
      
      
      ________________________________
