### ISSUE TITLE
Tree view reorganization causes fatal error

### ISSUE THREAD

**Issue by knyipab** [ImpulseAdventure/GUIslice-Builder#63]
### How to reproduce to bug
1. Create a tree view like this
![image](https://user-images.githubusercontent.com/46513942/73589014-5fa7a300-450b-11ea-8745-b5f8859d5f40.png)
2. Drag E_ELEM_TEXT1 below E_ELEM_TEXT2
3. Fatal error

### Side-issue
Besides, the drag-and-drop reorganization is not right. Let say for a tree view like this:
![image](https://user-images.githubusercontent.com/46513942/73589051-1c99ff80-450c-11ea-9b70-3435fedac77c.png)
E_ELEM_TEXT2 cannot be placed between E_ELEM_TEXT3 and E_ELEM_TEXT, nor below E_ELEM_TEXT4. 

Example project:
[gui2.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4142300/gui2.zip)

Environment: 0.13.b013 on Windows 10

**Comment by Pconti31** [comment]
Java's JTree works fine and is well documented when drag and drop is between different Java Swing components but doing a drag within the JTree is undocumented and a bit of black magic.
When dealing with a branch I have found no way to put an element below the final leaf object
within the branch at least not without very destructive behavior like placing it at the root level.

So the work-around for example 1 above is to simply select E_ELEM_TEXT2 and drag it above
E_ELEM_TEXT1.  Of course we shouldn't crash so I'll look into that case.  I reproduced the crash but in the future if you get a crash please post the crash file.

Example 2, select and drag E_ELEM_TEXT4 and drop above whatever.   E_ELEM_TEXT2 not moving between E_ELEM_TEXT3 and E_ELEM_TEXT4 is most likely from me trying to prevent the crash from example 1 above and doing a poor job of it. I'll add new bug report.

Paul--

**Comment by Pconti31** [comment]
Bug 137 is fixed in Release 0.13.b014.

Note that the crash is fixed and the movement of E_ELEM_TEXT2 between E_ELEM_TEXT3 and E_ELEM_TEXT4 now also works.   Not being able to drag E_ELEM_TEXT1 below E_ELEM_TEXT2 in example 1 above is a feature of Java Swing's JTree but again you can simply select E_ELEM_TEXT2 and drag above E_ELEM_TEXT1  to get the same effect.
Paul--
