### ISSUE TITLE
Preference to force all code to be generated

### ISSUE THREAD

**Issue by dduehren** [ImpulseAdventure/GUIslice-Builder#76]
**Describe the solution you'd like**
It appears that Builder tries to preserve the underlying code and only make certain changes.  That at least is the behavior I see.  But it isn't compatible with being sure that the design from the top agrees with the code below.  I'd like to see an option that forces the builder to generate the code as though it were the first time on a project.  That way for backups, etc I could be sure that I could generate from the top.  

**Additional context**

**Comment by Pconti31** [comment]
version 0.13.b024 has added in the options->General tab
"Preserve Button Callbacks?" property.  Set to false and the Builder will always recreate
Button case statements.

**Comment by dduehren** [comment]
Thanks

Sent from my iPhone

David Duehren

> On Apr 8, 2020, at 2:47 PM, Paul Conti <notifications@github.com> wrote:
> 

﻿
version 0.13.b024 has added in the options->General tab
"Preserve Button Callbacks?" property. Set to false and the Builder will always recreate
Button case statements.

**Comment by dduehren** [comment]
As a followup, I'd like to put some of the elements in Flash and change the size of the buttons on the keypad.  But when I change the preferences and generate code, nothing changes.  This is not the desired behavior.

**Comment by ImpulseAdventure** [comment]
For future reference, @dduehren's additional question regarding the change of buttons / generation has been resolved in a separate email thread; the code generation looks to be working correctly. If there are any outstanding issues, please open a new issue. thanks!
