### ISSUE TITLE
Lack of colors/crash 'feature'

### ISSUE THREAD

**Issue by PhantomSage** [ImpulseAdventure/GUIslice-Builder#79]
**Describe the bug**
On windows 10, if I start GuiSlicer directly from the jar file, it will not find the list of colors, thus resulting in an index out of bounds exception when trying to edit the colors.
I didn't want to run the .exe but rather started it from the .jar file directly, and I assume it didn't find templates\default_colors.csv by itself.
This is not a serious problem, starting it via normal means, or via "java -jar lib\builderxxx.jar" resolves the issues, but thought I let you know.

**To Reproduce**
Unpack the Linux archive on a windows machine.
double-click the ,jar file in the lib catalog.
Open/Make a project
Open the color dialog on a object
Edit the color (e.g. red [-])
"Fatal error"

**Expected behavior**
Not a big problem, fine if you close it without fixing.
But be aware, and let others find out that you have to be in the correct catalogue when you invoke the .jar file to find the bundled resources.

**Crash log / Project files**
If you experienced a crash, please attach the following to help us diagnose the cause:
- Attach a ZIP file containing the project folder including the `*.prj` and `*.ino` or `*.c` and `*.ino.bak`.

**Screenshots**

**Version**
- Builder version: Latest downloaded today
- OS: Hybrid running ,jar on a Windows machine

**Comment by Pconti31** [comment]
if you want to just double click you need a fatjar designed for this purpose.
use the osx version of the builder.
And yes I'm not going to fix it for windows.

By the way I'm issuing a hotfix today, jump to page is broken so please download
version 0.13.b025.1 when available.
