### ISSUE TITLE
Support for Teensy fonts

### ISSUE THREAD

**Issue by ImpulseAdventure** [ImpulseAdventure/GUIslice-Builder#89]
**Describe the solution you'd like**
The Teensy (and several other devices) use the extended font modes of GUIslice to select between various fonts (eg. internal, external ROM, custom, etc.). It would be very useful if the Builder were to add support for the insertion of the gslc_FontSetMode() API so that these devices/fonts could be supported directly

**Additional context**
Ideally, the `arduinofonts.csv` file could add a column to record the `FONTREF_MODE` setting. If the `FONTREF_MODE` value were non-blank, then the gslc_FontSetMode() API would be called after gslc_FontSet().

Please see **ex04_ard_ctrls** for an example.

In the case of the Teensy example, a corresponding arduinofonts.csv row might show:
`Teensy,Arial,font_Arial.h,NULL,E_T3_ARIAL12,GSLC_FONTREF_PTR,&Arial_12,GSLC_FONTREF_MODE_1`

Reference: Builder issue list item #166

**Comment by Pconti31** [comment]
Under development and will be included with release 0.14.b005
Paul--

**Comment by Pconti31** [comment]
Addressed in Release 0.15.0
