### ISSUE TITLE
Is it possible to add support for LittleVGL？

### ISSUE THREAD

**Issue by guo652917087** [ImpulseAdventure/GUIslice-Builder#91]
Hi，
   Is it possible to add support for LittleVGL？
   "LittleVGL" is also written in C language.

**Comment by Pconti31** [comment]
@guo652917087 
The library appears to be competitor to GUIslice API, supporting MCUs starting with with 80 kB Flash and 12 kB RAM.
It's an interesting project but they also seem to be working on a GUI design tool so it would seem pointless for me to get involved.  Frankly I have enough on my plate just with GUIslice API support.
Thank you for your interest.

Paul--
