### ISSUE TITLE
Moto_mono24 not in Arduino .csv file

### ISSUE THREAD

**Issue by dduehren** [ImpulseAdventure/GUIslice-Builder#92]
This is a minor issue.  mono22 is repeated and the 2nd one should be mono24

**Comment by Pconti31** [comment]
@dduehren Thanks for the catch!
I'll make the fix in 0.14.b005, just waiting on Calvin to finish editing this file adding in teensy fonts and we should be good to go.
Paul--

**Comment by Pconti31** [comment]
Addressed in Release 0.15.0
