### ISSUE TITLE
Crashing on OSX

### ISSUE THREAD

**Issue by tanthony1** [ImpulseAdventure/GUIslice-Builder#96]
**Describe the bug**
Made a couple of pages and then the application crashed. 

Cannot work on the project again. 
Crashes with crash report beign written to logs. 

**To Reproduce**
1. start application
2. Open Project
3. make any changes or click Save as 
4. Application crashes and crash log is written with pop up box showing location

**Expected behavior**
application does not crash 

**Crash log / Project files**
If you experienced a crash, please attach the following to help us diagnose the cause:
- Attach a ZIP file containing the project folder including the `*.prj` and `*.ino` or `*.c` and ``*.ino.bak`.class java.lang.IllegalArgumentException: image == null!
javax.imageio.ImageTypeSpecifier.createFromRenderedImage(ImageTypeSpecifier.java:925)
javax.imageio.ImageIO.getWriter(ImageIO.java:1592)
javax.imageio.ImageIO.write(ImageIO.java:1578)
builder.common.CommonUtils.encodeToString(CommonUtils.java:183)
builder.models.ImageModel.writeModel(ImageModel.java:426)
builder.widgets.Widget.writeObject(Widget.java:336)
builder.views.PagePane.backup(PagePane.java:927)
builder.controller.Controller.saveProject(Controller.java:860)
builder.views.RibbonListener.actionPerformed(RibbonListener.java:739)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
javax.swing.AbstractButton.doClick(AbstractButton.java:376)
javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
java.awt.Component.processMouseEvent(Component.java:6525)
javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
java.awt.Component.processEvent(Component.java:6290)
java.awt.Container.processEvent(Container.java:2234)
java.awt.Component.dispatchEventImpl(Component.java:4881)
java.awt.Container.dispatchEventImpl(Container.java:2292)
java.awt.Component.dispatchEvent(Component.java:4703)
java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
java.awt.Container.dispatchEventImpl(Container.java:2278)
java.awt.Window.dispatchEventImpl(Window.java:2750)
java.awt.Component.dispatchEvent(Component.java:4703)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
java.awt.EventQueue$4.run(EventQueue.java:731)
java.awt.EventQueue$4.run(EventQueue.java:729)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Screenshots**

**Version**
- Builder version: 0.14.b004
- OS: OSX catalina - java says is updated (no updates available) 8 v 51 

**Additional context**

**Comment by Pconti31** [comment]
I need the project folder zip'ed to debug the issue.
The traceback says it has a problem with an image file.
Maybe you could also include the images you used and give me an idea of what widgets you were using that required images.

**Comment by Pconti31** [comment]
Since you haven't provided any additional information there isn't much I can do to hunt down the issue.  However, I have just taken some proactive steps in the next release 0.14.b005.  I assume your problem with the image whatever it was caused the local copy of the image to be NULL.  This in turn caused the crash when saving the project.  The new version of the Builder will do a better job with reporting errors back to you when first creating the image widget.  A dialog box will show up posting the error and then maybe we can figure out what the issue is with that image.  In an error case the the image widget will no longer be created so saving the projects will not crash.  I have also added apache's log4j2 tracing to the Builder in the next release so I can hunt down issues when a project file can't be provided.

**Comment by Pconti31** [comment]
While I can't test your problem, debugging info has been added to Release 0.15.0 
If it happens with this release include the GUIsliceBuilder/logs/builder.log file and post a new issue.
