### ISSUE TITLE
Frame/fill/glow color not generated for sliders

### ISSUE THREAD

**Issue by JohannesWilde** [ImpulseAdventure/GUIslice-Builder#97]
A very good day to you.

Using GuiSlice Builder 0.14.b004 for sliders not line similar to the following is generated:

`gslc_ElemSetCol(&m_gui,pElemRef,GSLC_COL_BLUE,GSLC_COL_GRAY_LT2,GSLC_COL_YELLOW);`

i.e. the selected colors for frame, fill and glow are not adopted.

Should you require more input - feel free to ask. To reproduce this finding, however, one just needs to create a slider, change the frame/fill/glow color and generate code.

An MWI is attached as well as the output generated.

[MWI.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4977424/MWI.zip)

**Comment by Pconti31** [comment]
@JohannesWilde I also discovered this a few months back and checked in the fix to the pconti-14-005 branch.  It will show up in the next release which Calvin tells me will now be called 0.15.0
and he will have a new GUIslice API 0.15.0 also.
I don't remember listing this issue in the 0.14.005 branch readme but I will.  You can see other bug fixes and new enhancements that are pending by switching to this branch and looking over its readme.
Calvin has completed his survey of Displays and Font handling and given me his report.  The ball is now in my court to make some changes and then I can generate a new release.  Barring any unforeseen problems it should be ready  in a few weeks.  I'll be sure to regression test your issue before release.
Paul--

**Comment by JohannesWilde** [comment]
@Pconti31 Sound good - thanks a lot.

**Comment by Pconti31** [comment]
Addressed in Release 0.15.0
