### ISSUE TITLE
Load Additional Fonts that can be used with gslc_DrvDrawTxtAlign and other functions

### ISSUE THREAD

**Issue by tpitman** [ImpulseAdventure/GUIslice-Builder#98]
**Describe the solution you'd like**
The builder outputs code in the generated _GSLC.h file to include font headers and load the fonts. The fonts that are loaded are only those reference in the builder project. I would like to specify additional fonts to be loaded into the system so that I can use them with manual drawing of text.

**Comment by Pconti31** [comment]
Seems reasonable.  I'll schedule it for the next release 0.15.0

Paul--

**Comment by Pconti31** [comment]
Addressed in Release 0.15.0
